language: java
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
    -in secrets.tar.enc -out secrets.tar -d
  - chmod +x mvnw
  - tar xvf secrets.tar
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)