language: java
jdk:
- oraclejdk11
before_install:
- openssl aes-256-cbc -K $encrypted_89b963f6a196_key -iv $encrypted_89b963f6a196_iv
  -in src\\main\\resources\\pmapi.p12.enc -out src\\main\\resources\\pmapi.p12 -d
- openssl aes-256-cbc -K $encrypted_cb1d1588754e_key -iv $encrypted_cb1d1588754e_iv
  -in src\\main\\resources\\application.yml.enc -out src\\main\\resources\\application.yml
  -d
- openssl aes-256-cbc -K $encrypted_630c6e19e142_key -iv $encrypted_630c6e19e142_iv
  -in src\\main\\java\\com\\chillibits\\particulatematterapi\\shared\\Credentials.java.enc
  -out src\\main\\java\\com\\chillibits\\particulatematterapi\\shared\\Credentials.java
  -d
- chmod +x mvnw